// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forma.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105050530_AddUserEmailIdxUqConstraint")]
    partial class AddUserEmailIdxUqConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forma.Api.Models.FieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FieldTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldTypeId = 1,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 2,
                            FieldTypeId = 2,
                            Name = "Paragraph"
                        },
                        new
                        {
                            Id = 3,
                            FieldTypeId = 3,
                            Name = "Number"
                        },
                        new
                        {
                            Id = 4,
                            FieldTypeId = 4,
                            Name = "Checkbox"
                        },
                        new
                        {
                            Id = 5,
                            FieldTypeId = 5,
                            Name = "Toggle"
                        },
                        new
                        {
                            Id = 6,
                            FieldTypeId = 6,
                            Name = "Dropdown"
                        },
                        new
                        {
                            Id = 7,
                            FieldTypeId = 7,
                            Name = "Date"
                        });
                });

            modelBuilder.Entity("Forma.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
